name: Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'
      - 'hotfix-*'

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v2.4.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: npm install
        run: |
          npm run install --workspaces

      - run: npx --prefix ./packages/allure-playwright playwright install chromium --with-deps

      - name: npm build
        run: |
          npm run build
      - name: prettier:check
        run: |
          npm run prettier:check
      - name: npm run lint
        run: |
          npm run lint
      - name: npm test
        run: |
          npm run test

