name: Publish

on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - name: npm install, build
        run: |
          npm install --workspaces
          npm run build
      - run: npm publish --workspaces
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
